### ISSUE TITLE
Tests start an instance of the server

### ISSUE THREAD

**Issue by lpil** [redbadger/badger-brain#35]
* Slower than not starting it
* Causes EADDRINUSE error if tests are run twice in the same node instance (i.e. with test watcher for TDD)
* Possible strong coupling of app creation code with app running code

**Comment by jameshopkins** [comment]
What's invoking the creation of a server in the context of the tests?

**Comment by lpil** [comment]
Haven't looked yet, just wanted to make a note here before I forget or fall down a rabbit hole.

**Comment by bkspace** [comment]
@lpil - in test script 'mocha lib/*' is launching the server

package.json --> scripts --> test: "mocha 'lib/**/*.spec.js'" will sort it

**Comment by lpil** [comment]
I think there's probably stuff we want to test in that app module. I'd like to split the app creation from app running, like we do in react.london
