### ISSUE TITLE
Prismic allows publishing of documents we consider invalid. This could cause clients to crash

### ISSUE THREAD

**Issue by lpil** [redbadger/badger-brain#43]
Prismic has no method for doing validation, and no concept of required fields. This is problematic for us as it's possible to publish a document that has insufficient content for clients to render successfully.

One thing we can do to help avoid this happening is to implement a new prismic preview on Badger Brain that accepts the content of the document and then compares it to the schema and informs the user which required fields are missing, if any.

This makes it the user's responsibility to check the preview and fill in missing fields rather than their responsibility to remember which fields are required. This should reduce the likelyhood of human error here.

**Comment by asavin** [comment]
Soo we had a discussion on what is the best approach, and here is the outcome:

## Motivation

1. Clients should not explode in case the document is invalid
2. Admin user should be notified about invalid data in the document, ideally before the document is published

## Solution proposal

1. Badger Brain to implement a schema validation layer. It would validate every single document passing through BB. If the document has failed validation check, that document would be omitted from the response. We can re-use same Prismic custom schema definitions that are already stored in BB repo, with added flags for required fields.

2. In addition to fields validation we can implement preview route on BB which can be used by an admin user during document creation. This way admin user could invoke that preview before the document is published to get immediate feedback if the document is valid. Clients are also free to implement preview functionality, which is useful when admin wants to preview new document on the actual site, with styles and layouts. BB preview would be a simple list of failures, or a big OK.

**Comment by asavin** [comment]
Also, once we implement schema validation on BB, we could even notify the admin via email in case document fails validation.
